import type { Metadata } from "next";
import { Josefin_Sans } from 'next/font/google'; 
import "./globals.css";

const josefin = Josefin_Sans({
  variable: "--font-josefin",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "alison zou",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${josefin.variable} ${josefin.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
